[package]
name = "sdkwork-api-llm-standalone-gateway"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sdkwork-api-llm-standalone-gateway"
path = "src/main.rs"

[dependencies]
sdkwork_api_llm_assembly.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sdkwork-web-bootstrap.workspace = true

