-- SDKWork llm consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_Llm_baseline.sql
-- Consolidated legacy baseline for sdkwork-llm database module.
-- source: plugins/sdkwork-llm-plugin-native-sql/migrations/postgres/V202606100001__llm_phase1.sql

CREATE TABLE IF NOT EXISTS llm_space (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  organization_id BIGINT NOT NULL DEFAULT 0,
  owner_subject_type VARCHAR(32) NOT NULL,
  owner_subject_id VARCHAR(128) NOT NULL,
  space_type VARCHAR(32) NOT NULL,
  display_name VARCHAR(200) NOT NULL,
  default_scope VARCHAR(32) NOT NULL,
  lifecycle_status VARCHAR(32) NOT NULL,
  metadata_json JSONB,
  policy_json JSONB,
  created_by BIGINT,
  updated_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_space_uuid
  ON llm_space (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_space_owner_type
  ON llm_space (tenant_id, owner_subject_type, owner_subject_id, space_type);

CREATE TABLE IF NOT EXISTS llm_event (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES llm_space(id),
  user_id BIGINT,
  actor_type VARCHAR(32) NOT NULL,
  actor_id VARCHAR(128),
  session_id VARCHAR(128),
  trace_id VARCHAR(128),
  request_id VARCHAR(64),
  idempotency_key VARCHAR(128),
  event_type VARCHAR(64) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  source_ref VARCHAR(256),
  event_time TIMESTAMPTZ NOT NULL,
  payload_json JSONB NOT NULL,
  payload_hash VARCHAR(128) NOT NULL,
  sensitivity_level VARCHAR(32) NOT NULL,
  ingestion_status VARCHAR(32) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_event_uuid
  ON llm_event (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_event_idempotency
  ON llm_event (tenant_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS llm_record (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES llm_space(id),
  user_id BIGINT,
  scope VARCHAR(32) NOT NULL,
  memory_type VARCHAR(32) NOT NULL,
  subject VARCHAR(256),
  predicate VARCHAR(128),
  object_text TEXT NOT NULL,
  canonical_text TEXT NOT NULL,
  summary_text TEXT,
  language VARCHAR(16),
  confidence DECIMAL(5,4) NOT NULL,
  evidence_count INTEGER NOT NULL DEFAULT 0,
  contradiction_count INTEGER NOT NULL DEFAULT 0,
  importance_score DECIMAL(5,4) NOT NULL,
  recency_score DECIMAL(5,4) NOT NULL,
  habit_strength DECIMAL(5,4),
  valid_from TIMESTAMPTZ,
  valid_to TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  status VARCHAR(32) NOT NULL,
  sensitivity_level VARCHAR(32) NOT NULL,
  metadata_json JSONB,
  tags_json JSONB,
  supersedes_memory_id BIGINT REFERENCES llm_record(id),
  superseded_by_memory_id BIGINT REFERENCES llm_record(id),
  created_by BIGINT,
  updated_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_record_uuid
  ON llm_record (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_llm_record_scope_type_status
  ON llm_record (tenant_id, space_id, scope, memory_type, status, updated_at);

CREATE TABLE IF NOT EXISTS llm_record_source (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  memory_id BIGINT NOT NULL REFERENCES llm_record(id),
  event_id BIGINT NOT NULL REFERENCES llm_event(id),
  source_role VARCHAR(32) NOT NULL,
  confidence_delta DECIMAL(5,4),
  created_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_record_source_pair
  ON llm_record_source (tenant_id, memory_id, event_id, source_role);

CREATE TABLE IF NOT EXISTS llm_candidate (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES llm_space(id),
  user_id BIGINT,
  candidate_type VARCHAR(32) NOT NULL,
  memory_type VARCHAR(32) NOT NULL,
  proposed_text TEXT NOT NULL,
  proposed_payload_json JSONB,
  target_memory_id BIGINT REFERENCES llm_record(id),
  evidence_json JSONB,
  confidence DECIMAL(5,4) NOT NULL,
  novelty_score DECIMAL(5,4),
  risk_score DECIMAL(5,4),
  decision_state VARCHAR(32) NOT NULL,
  decision_reason VARCHAR(256),
  decided_by BIGINT,
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_candidate_uuid
  ON llm_candidate (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_habit (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES llm_space(id),
  user_id BIGINT NOT NULL,
  habit_key VARCHAR(160) NOT NULL,
  habit_type VARCHAR(64) NOT NULL,
  description TEXT NOT NULL,
  stage VARCHAR(32) NOT NULL,
  strength DECIMAL(5,4) NOT NULL,
  confidence DECIMAL(5,4) NOT NULL,
  support_count INTEGER NOT NULL DEFAULT 0,
  last_signal_at TIMESTAMPTZ,
  promoted_memory_id BIGINT REFERENCES llm_record(id),
  decay_after TIMESTAMPTZ,
  metadata_json JSONB,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_habit_key
  ON llm_habit (tenant_id, space_id, user_id, habit_key);

CREATE TABLE IF NOT EXISTS llm_retrieval_trace (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT,
  retrieval_profile_id BIGINT,
  actor_id VARCHAR(128),
  query_text TEXT,
  query_hash VARCHAR(128) NOT NULL,
  retrievers_json JSONB,
  latency_ms INTEGER,
  result_count INTEGER NOT NULL DEFAULT 0,
  degraded BOOLEAN NOT NULL DEFAULT FALSE,
  metadata_json JSONB,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_retrieval_trace_uuid
  ON llm_retrieval_trace (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_retrieval_hit (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  retrieval_trace_id BIGINT NOT NULL REFERENCES llm_retrieval_trace(id),
  memory_id BIGINT REFERENCES llm_record(id),
  retriever_name VARCHAR(64) NOT NULL,
  result_rank INTEGER NOT NULL,
  raw_score DECIMAL(10,6),
  fused_score DECIMAL(10,6),
  explanation_json JSONB,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_llm_retrieval_hit_trace_rank
  ON llm_retrieval_hit (tenant_id, retrieval_trace_id, result_rank);

CREATE TABLE IF NOT EXISTS llm_context_pack (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  retrieval_trace_id BIGINT REFERENCES llm_retrieval_trace(id),
  actor_id VARCHAR(128),
  query_text TEXT,
  pack_json JSONB NOT NULL,
  estimated_tokens INTEGER NOT NULL,
  truncated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_context_pack_uuid
  ON llm_context_pack (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_index (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT,
  index_kind VARCHAR(32) NOT NULL,
  implementation_profile_id BIGINT,
  provider_binding_id BIGINT,
  schema_version VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  rebuild_cursor VARCHAR(256),
  config_json JSONB,
  last_rebuilt_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_index_uuid
  ON llm_index (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_retrieval_profile (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT,
  name VARCHAR(160) NOT NULL,
  strategy VARCHAR(64) NOT NULL,
  retrievers_json JSONB NOT NULL,
  fusion_policy_json JSONB,
  rerank_policy_json JSONB,
  top_k INTEGER NOT NULL,
  context_budget_tokens INTEGER NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_retrieval_profile_uuid
  ON llm_retrieval_profile (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_implementation_profile (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(160) NOT NULL,
  implementation_kind VARCHAR(64) NOT NULL,
  role VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  capability_json JSONB NOT NULL,
  config_json JSONB,
  rollout_json JSONB,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_implementation_profile_uuid
  ON llm_implementation_profile (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_provider_binding (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  provider_kind VARCHAR(32) NOT NULL,
  provider_code VARCHAR(128) NOT NULL,
  display_name VARCHAR(160) NOT NULL,
  endpoint_ref VARCHAR(256),
  secret_ref VARCHAR(256),
  model_ref VARCHAR(256),
  capabilities_json JSONB NOT NULL,
  config_json JSONB,
  health_state VARCHAR(32) NOT NULL,
  last_health_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_provider_binding_uuid
  ON llm_provider_binding (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_eval_run (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  eval_type VARCHAR(64) NOT NULL,
  state VARCHAR(32) NOT NULL,
  metrics_json JSONB,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_eval_run_uuid
  ON llm_eval_run (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_audit_log (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  actor_type VARCHAR(32) NOT NULL,
  actor_id VARCHAR(128),
  action VARCHAR(128) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id VARCHAR(128),
  request_id VARCHAR(64),
  trace_id VARCHAR(128),
  result VARCHAR(32) NOT NULL,
  reason VARCHAR(256),
  metadata_json JSONB,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_audit_log_uuid
  ON llm_audit_log (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_outbox_event (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  event_version VARCHAR(32) NOT NULL,
  payload_json JSONB NOT NULL,
  publish_state VARCHAR(32) NOT NULL,
  published_at TIMESTAMPTZ,
  retry_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_outbox_event_uuid
  ON llm_outbox_event (tenant_id, uuid);

-- baseline source: ddl/baseline/sqlite/0001_Llm_sqlite_baseline.sql
-- Consolidated SQLite baseline for sdkwork-llm database module.
-- source: plugins/sdkwork-llm-plugin-native-sql/migrations/sqlite/V202606100001__llm_phase1.sql

CREATE TABLE IF NOT EXISTS llm_space (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  organization_id INTEGER NOT NULL DEFAULT 0,
  owner_subject_type TEXT NOT NULL,
  owner_subject_id TEXT NOT NULL,
  space_type TEXT NOT NULL,
  display_name TEXT NOT NULL,
  default_scope TEXT NOT NULL,
  lifecycle_status TEXT NOT NULL,
  metadata_json TEXT,
  policy_json TEXT,
  created_by INTEGER,
  updated_by INTEGER,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  version INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_space_uuid
  ON llm_space (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_space_owner_type
  ON llm_space (tenant_id, owner_subject_type, owner_subject_id, space_type);

CREATE TABLE IF NOT EXISTS llm_event (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  space_id INTEGER NOT NULL,
  user_id INTEGER,
  actor_type TEXT NOT NULL,
  actor_id TEXT,
  session_id TEXT,
  trace_id TEXT,
  request_id TEXT,
  idempotency_key TEXT,
  event_type TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_ref TEXT,
  event_time TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  payload_hash TEXT NOT NULL,
  sensitivity_level TEXT NOT NULL,
  ingestion_status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (space_id) REFERENCES llm_space(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_event_uuid
  ON llm_event (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_event_idempotency
  ON llm_event (tenant_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS llm_record (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  space_id INTEGER NOT NULL,
  user_id INTEGER,
  scope TEXT NOT NULL,
  memory_type TEXT NOT NULL,
  subject TEXT,
  predicate TEXT,
  object_text TEXT NOT NULL,
  canonical_text TEXT NOT NULL,
  summary_text TEXT,
  language TEXT,
  confidence REAL NOT NULL,
  evidence_count INTEGER NOT NULL DEFAULT 0,
  contradiction_count INTEGER NOT NULL DEFAULT 0,
  importance_score REAL NOT NULL,
  recency_score REAL NOT NULL,
  habit_strength REAL,
  valid_from TEXT,
  valid_to TEXT,
  expires_at TEXT,
  status TEXT NOT NULL,
  sensitivity_level TEXT NOT NULL,
  metadata_json TEXT,
  tags_json TEXT,
  supersedes_memory_id INTEGER,
  superseded_by_memory_id INTEGER,
  created_by INTEGER,
  updated_by INTEGER,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  version INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (space_id) REFERENCES llm_space(id),
  FOREIGN KEY (supersedes_memory_id) REFERENCES llm_record(id),
  FOREIGN KEY (superseded_by_memory_id) REFERENCES llm_record(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_record_uuid
  ON llm_record (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_llm_record_scope_type_status
  ON llm_record (tenant_id, space_id, scope, memory_type, status, updated_at);

CREATE TABLE IF NOT EXISTS llm_record_source (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  memory_id INTEGER NOT NULL,
  event_id INTEGER NOT NULL,
  source_role TEXT NOT NULL,
  confidence_delta REAL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (memory_id) REFERENCES llm_record(id),
  FOREIGN KEY (event_id) REFERENCES llm_event(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_record_source_pair
  ON llm_record_source (tenant_id, memory_id, event_id, source_role);

CREATE TABLE IF NOT EXISTS llm_candidate (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  space_id INTEGER NOT NULL,
  user_id INTEGER,
  candidate_type TEXT NOT NULL,
  memory_type TEXT NOT NULL,
  proposed_text TEXT NOT NULL,
  proposed_payload_json TEXT,
  target_memory_id INTEGER,
  evidence_json TEXT,
  confidence REAL NOT NULL,
  novelty_score REAL,
  risk_score REAL,
  decision_state TEXT NOT NULL,
  decision_reason TEXT,
  decided_by INTEGER,
  decided_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (space_id) REFERENCES llm_space(id),
  FOREIGN KEY (target_memory_id) REFERENCES llm_record(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_candidate_uuid
  ON llm_candidate (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_habit (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  space_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  habit_key TEXT NOT NULL,
  habit_type TEXT NOT NULL,
  description TEXT NOT NULL,
  stage TEXT NOT NULL,
  strength REAL NOT NULL,
  confidence REAL NOT NULL,
  support_count INTEGER NOT NULL DEFAULT 0,
  last_signal_at TEXT,
  promoted_memory_id INTEGER,
  decay_after TEXT,
  metadata_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (space_id) REFERENCES llm_space(id),
  FOREIGN KEY (promoted_memory_id) REFERENCES llm_record(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_habit_key
  ON llm_habit (tenant_id, space_id, user_id, habit_key);

CREATE TABLE IF NOT EXISTS llm_retrieval_trace (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  space_id INTEGER,
  retrieval_profile_id INTEGER,
  actor_id TEXT,
  query_text TEXT,
  query_hash TEXT NOT NULL,
  retrievers_json TEXT,
  latency_ms INTEGER,
  result_count INTEGER NOT NULL DEFAULT 0,
  degraded INTEGER NOT NULL DEFAULT 0,
  metadata_json TEXT,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_retrieval_trace_uuid
  ON llm_retrieval_trace (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_retrieval_hit (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  retrieval_trace_id INTEGER NOT NULL,
  memory_id INTEGER,
  retriever_name TEXT NOT NULL,
  result_rank INTEGER NOT NULL,
  raw_score REAL,
  fused_score REAL,
  explanation_json TEXT,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (retrieval_trace_id) REFERENCES llm_retrieval_trace(id),
  FOREIGN KEY (memory_id) REFERENCES llm_record(id)
);

CREATE INDEX IF NOT EXISTS idx_llm_retrieval_hit_trace_rank
  ON llm_retrieval_hit (tenant_id, retrieval_trace_id, result_rank);

CREATE TABLE IF NOT EXISTS llm_context_pack (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  retrieval_trace_id INTEGER,
  actor_id TEXT,
  query_text TEXT,
  pack_json TEXT NOT NULL,
  estimated_tokens INTEGER NOT NULL,
  truncated INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  FOREIGN KEY (retrieval_trace_id) REFERENCES llm_retrieval_trace(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_context_pack_uuid
  ON llm_context_pack (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_index (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  space_id INTEGER,
  index_kind TEXT NOT NULL,
  implementation_profile_id INTEGER,
  provider_binding_id INTEGER,
  schema_version TEXT NOT NULL,
  status TEXT NOT NULL,
  rebuild_cursor TEXT,
  config_json TEXT,
  last_rebuilt_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_index_uuid
  ON llm_index (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_retrieval_profile (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  space_id INTEGER,
  name TEXT NOT NULL,
  strategy TEXT NOT NULL,
  retrievers_json TEXT NOT NULL,
  fusion_policy_json TEXT,
  rerank_policy_json TEXT,
  top_k INTEGER NOT NULL,
  context_budget_tokens INTEGER NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_retrieval_profile_uuid
  ON llm_retrieval_profile (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_implementation_profile (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  implementation_kind TEXT NOT NULL,
  role TEXT NOT NULL,
  status TEXT NOT NULL,
  capability_json TEXT NOT NULL,
  config_json TEXT,
  rollout_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_implementation_profile_uuid
  ON llm_implementation_profile (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_provider_binding (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  provider_kind TEXT NOT NULL,
  provider_code TEXT NOT NULL,
  display_name TEXT NOT NULL,
  endpoint_ref TEXT,
  secret_ref TEXT,
  model_ref TEXT,
  capabilities_json TEXT NOT NULL,
  config_json TEXT,
  health_state TEXT NOT NULL,
  last_health_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_provider_binding_uuid
  ON llm_provider_binding (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_eval_run (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  eval_type TEXT NOT NULL,
  state TEXT NOT NULL,
  metrics_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_eval_run_uuid
  ON llm_eval_run (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_audit_log (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  actor_type TEXT NOT NULL,
  actor_id TEXT,
  action TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT,
  request_id TEXT,
  trace_id TEXT,
  result TEXT NOT NULL,
  reason TEXT,
  metadata_json TEXT,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_audit_log_uuid
  ON llm_audit_log (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS llm_outbox_event (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  tenant_id INTEGER NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  event_version TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  publish_state TEXT NOT NULL,
  published_at TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_llm_outbox_event_uuid
  ON llm_outbox_event (tenant_id, uuid);
